enum Direction {
  ltr,
  rtl,
}

class Es {
  Direction $direction = Direction.ltr;
  String $name = "Español";
  String $code = "es";

  Map<String, String> dictionary = {
    // common
    "cancel": "Cancelar",
    "close": "Cerrar",
    "save": "Guardar",
    "reset": "Restablecer",
    "continue": "Continuar",
    "add": "Agregar",
    "edit": "Editar",
    "delete": "Eliminar",
    "archive": "Archivar",
    "restore": "Restaurar",
    "logout": "Cerrar sesión",
    "noResultsFound": "No se encontraron resultados",
    "home": "Inicio",
    "calendar": "Calendario",
    "gettingImages": "Obteniendo imágenes",

    // call
    "callLaboratory": "Llamar al laboratorio",
    "callPatient": "Llamar al paciente",
    "emailDoctor": "Enviar correo al doctor",
    "callIssuer": "Llamar al emisor",

    // screens
    "settings": "Configuraciones",
    "dashboard": "Tablero",
    "appointments": "Citas",
    "patients": "Pacientes",
    "doctors": "Doctores",
    "labworks": "Trabajos de laboratorio",
    "statistics": "Estadísticas",

    // dashboard
    "admin": "Administrador",
    "fullStats": "Estadísticas completas",
    "payments": "Pagos",
    "appointmentsToday": "Citas de hoy",
    "patientsToday": "Pacientes de hoy",
    "newPatientsToday": "Nuevos pacientes de hoy",
    "paymentsMadeToday": "Pagos realizados hoy",
    "modeAdmin": "ADMINISTRADOR",
    "modeUser": "USUARIO",
    "modeOffline": "SIN CONEXIÓN",
    "onceConnectionIsStable":
        "Una vez que su conexión sea estable, puede usar el botón en la esquina superior derecha para reconectar.",
    "unRestrictedAccess": "acceso sin restricciones en la aplicación",
    "restrictedAccess":
        "acceso restringido a algunas pantallas según lo dictado por el administrador",
    "youAreCurrentlyIn": "Actualmente estás en",
    "mode": "modo",
    "youHave": "Tienes",
    "hello": "Hola",

    // datatable
    "archiveSelected": "Archivar seleccionados",
    "searchPlaceholder": "Buscar...",
    "showHideArchived": "Mostrar/Ocultar archivados",
    "showing": "Mostrando",
    "by": "Por",
    "byTitle": "Por título",
    "byDate": "Por fecha",
    "noItemsFound": "No se encontraron elementos",
    "filter": "Filtrar",

    // doctors
    "doctor": "Doctor",
    "newDoctor": "Nuevo doctor",
    "doctorDetails": "Detalles del doctor",
    "pastAppointments": "Citas pasadas",
    "upcomingAppointments": "Próximas citas",
    "doctorName": "Nombre del doctor",
    "doctorEmail": "Correo del doctor",
    "dutyDays": "Días de trabajo",
    "addAppointment": "Agregar cita",
    "lockToUsers":
        "Solo los siguientes usuarios pueden ver/editar los datos y citas de este doctor",
    "noUpcomingAppointmentsForThisDoctor":
        "No se encontraron próximas citas. Use el botón de abajo para registrar una nueva",

    // days and months
    "monday": "Lunes",
    "tuesday": "Martes",
    "wednesday": "Miércoles",
    "thursday": "Jueves",
    "friday": "Viernes",
    "saturday": "Sábado",
    "sunday": "Domingo",
    "january": "Enero",
    "february": "Febrero",
    "march": "Marzo",
    "april": "Abril",
    "may": "Mayo",
    "june": "Junio",
    "july": "Julio",
    "august": "Agosto",
    "september": "Septiembre",
    "october": "Octubre",
    "november": "Noviembre",
    "december": "Diciembre",

    // appointment card
    "appointment": "Cita",
    "patient": "Paciente",
    "photos": "Fotos",
    "pre-opNotes": "Notas preoperatorias",
    "post-opNotes": "Notas postoperatorias",
    "prescription": "Receta",
    "pay": "Pagar",
    "paid": "Pagado",
    "price": "Precio",
    "underpaid": "Pago insuficiente",
    "overpaid": "Pago excesivo",
    "fullyPaid": "Totalmente pagado",
    "paymentSummary": "Resumen de pago",
    "editingAppointment": "Editando cita",
    "after": "Después",
    "days": "días",
    "day": "día",
    "isDone": "La cita está hecha",

    // patients
    "patientDetails": "Detalles del paciente",
    "age": "Edad",
    "gender": "Género",
    "last visit": "Última visita",
    "total payments": "Pagos totales",
    "daysAgo": "hace días",
    "noVisits": "Sin visitas",
    "addNewPatient": "Agregar nuevo paciente",
    "name": "Nombre",
    "birthYear": "Año de nacimiento",
    "phone": "Teléfono",
    "email": "Correo electrónico",
    "address": "Dirección",
    "notes": "Notas",
    "patientTags": "Etiquetas del paciente",
    "male": "Masculino",
    "female": "Femenino",
    "noAppointmentsFound":
        "No se encontraron citas para este paciente, use el botón de abajo para agregar una nueva cita.",
    "editPatient": "Editar paciente",
    "editAppointment": "Editar cita",
    "patientPage": "Página web del paciente",
    "patientCanUseTheFollowing":
        "El paciente puede usar el siguiente enlace para acceder a sus citas, pagos y fotos.",
    "printQR": "Imprimir código QR",
    "dentalNotes": "Notas dentales",
    "showPrimary": "Mostrar primarios",
    "showPermanent": "Mostrar permanentes",
    "primary": "Primario",
    "permanent": "Permanente",
    "lower": "Inferior",
    "upper": "Superior",
    "left": "Izquierda",
    "right": "Derecha",
    "centralIncisor": "Incisivo central",
    "lateralIncisor": "Incisivo lateral",
    "canine": "Canino",
    "firstPremolar": "Primer premolar",
    "secondPremolar": "Segundo premolar",
    "firstMolar": "Primer molar",
    "secondMolar": "Segundo molar",
    "thirdMolar": "Tercer molar",
    "exportSelected": "Exportar seleccionados",
    "noPatientsSelected": "No hay pacientes seleccionados",

    // calendar (appointments)
    "allDoctors": "Todos los doctores",
    "noAppointmentsForThisDay": "No hay citas para este día",
    "weekAbbr": "S",
    "twoWeeksAbbr": "2S",
    "monthAbbr": "M",
    "today": "Hoy",
    "newPatient": "Nuevo paciente",
    "date": "Fecha",
    "changeDate": "Cambiar fecha",
    "changeTime": "Cambiar hora",
    "attention": "Atención",
    "doctorNotAvailable": "Uno de los doctores seleccionados podría no estar disponible en la fecha seleccionada.",
    "time": "Hora",
    "preOperativeNotes": "Notas preoperatorias",
    "selectDoctors": "Seleccionar doctores",
    "selectPatient": "Seleccionar paciente",
    "operativeDetails": "Detalles operativos",
    "postOperativeNotes": "Notas postoperatorias",
    "printPrescription": "Imprimir receta",
    "priceIn": "Precio en",
    "paidIn": "Pagado en",
    "gallery": "Galería",
    "link": "Enlace",
    "upload": "Subir",
    "camera": "Cámara",
    "emptyGallery": "Galería vacía",
    "noPhotos": "No se han subido fotos aún.",
    "importingPhotosFromLink": "Importando fotos desde enlace",
    "useThisForm":
      "Use este formulario para importar fotos desde enlaces compartidos, como Google Photos, o cualquier página web accesible que contenga fotos que desee agregar a esta cita.",
    "error": "Error",
    "enterLink": "Ingrese una URL que contenga fotos",
    "import": "Importar",

    // labworks
    "laboratory": "Laboratorio",
    "month": "mes",
    "newLabwork": "Nuevo trabajo de laboratorio",
    "labwork": "trabajo de laboratorio",
    "labworkTitle": "Título del trabajo de laboratorio",
    "orderNotes": "Notas del pedido",
    "unpaid": "No pagado",
    "noSuggestions": "Sin sugerencias",

    // expenses
    "expense": "Gasto",
    "expenses": "Gastos",
    "receipt": "Recibo",
    "title": "Título",
    "cost": "Costo",
    "issuer": "Emisor",
    "amount": "Cantidad",
    "amountIn": "Cantidad en",
    "status": "Estado",
    "due": "Vencido",
    "receiptTitle": "Título del recibo",
    "receiptNotes": "Notas del recibo",
    "newReceipt": "Nuevo recibo",
    "receiptTags": "Etiquetas del recibo",
    "receiptItems": "Elementos del recibo",
    "specificForDoctors": "Específico para los siguientes doctores",

    // stats
    "pickRange": "Seleccionar rango",
    "start": "Inicio",
    "end": "Fin",
    "weeks": "Semanas",
    "months": "Meses",
    "quarters": "Trimestres",
    "years": "Años",
    "appointmentsPer": "Citas por",
    "paymentsAndExpensesPer": "Pagos y gastos por",
    "newPatientsPer": "Nuevos pacientes por",
    "doneMissedPer": "Realizadas y perdidas por",
    "timeOfDay": "Hora del día",
    "dayOfWeek": "Día de la semana",
    "dayOfMonth": "Día del mes",
    "monthOfYear": "Mes del año",
    "patientsGender": "Género de los pacientes",
    "total": "Total",
    "in_Duration_": "en",
    "acquiredPatientsIn": "Pacientes adquiridos en",
    "doneAndMissedAppointmentsIn": "Citas realizadas y perdidas en",
    "distributionOfAppointments": "Distribución de citas",
    "maleAndFemalePatients": "Pacientes masculinos y femeninos",
    "done": "realizadas",
    "missed": "perdidas",

    // settings
    "currency": "Moneda",
    "currency_desc": "Código de moneda que se utilizará en toda la aplicación (por ejemplo, USD, EUR, IQD).",
    "phone_desc": "El número de teléfono se mostrará en impresiones y en la página web de los pacientes.",
    "prescriptionFooter": "Pie de página de la receta",
    "prescriptionFooter_desc": "Este texto se mostrará en la parte inferior de la receta.",
    "language": "Idioma",
    "language_desc": "El idioma de la interfaz para los menús, botones e información utilizada en toda la aplicación.",
    "startingDayOfWeek": "Día de inicio de la semana",
    "startingDayOfWeek_desc": "El día de la semana en que comienza la semana.",
    "dateFormat": "Formato de fecha",
    "dateFormat_desc": "Este formato se utilizará para mostrar fechas donde sea aplicable.",
    "cacheReset": "Restablecer caché",
    "cacheReset_desc":
      "Usando el botón de abajo, puede eliminar los datos guardados localmente (excepto las imágenes), esto resolvería algunos problemas de sincronización si está enfrentando alguno.",
    "month/day/year": "Mes/Día/Año",
    "day/month/year": "Día/Mes/Año",
    "appliesTo": "Se aplica a",
    "all": "Todos",
    "you": "tú",
    "initialSynchronization": "Sincronización inicial",
    "synchronizing": "Sincronizando",
    "clearingLocalData": "Borrando datos locales",

    // advanced settings: Backups
    "backups": "Copias de seguridad",
    "refresh": "Actualizar",
    "download": "Descargar",
    "createNew": "Crear nuevo",
    "restoreBackup": "Restaurar copia de seguridad",
    "restoreBackupWarning1":
      "Restaurar esta copia de seguridad sobrescribirá todos los datos en la aplicación actualmente. Cualquier cambio que haya realizado después de la fecha de esta copia de seguridad",
    "restoreBackupWarning2": "se perderá.\n\n¿Está seguro de que desea restaurar esta copia de seguridad?",
    "sureDeleteBackup": "¿Está seguro de que desea eliminar esta copia de seguridad?",
    "backupDate": "Fecha de la copia de seguridad",
    "useTheFollowingLinkToDownloadTheBackup": "Use el siguiente enlace para descargar la copia de seguridad",

    // advanced settings: Admins
    "admins": "Administradores",
    "accountCreated": "Cuenta creada",
    "editAdmin": "Editar administrador",
    "validEmailMustBeProvided": "Debe proporcionar un correo electrónico válido",
    "password": "Contraseña",
    "leaveBlankToKeepUnchanged": "Deje en blanco para mantener sin cambios",
    "updatingPassword": "Actualizando contraseña",
    "leaveItEmpty": "Deje el campo de contraseña vacío si no desea cambiarla.",
    "newAdmin": "Nuevo administrador",
    "minimumPasswordLength": "Contraseña de mínimo 10 caracteres",

    // advanced settings: Users
    "users": "Usuarios",
    "editUser": "Editar usuario",
    "newUser": "Nuevo usuario",

    // advanced settings: Permissions
    "permissions": "Permisos de usuario",
    "usersCanAccess": "Los usuarios pueden acceder",
    "permissionsNotice":
      "Los siguientes permisos se aplican a los usuarios listados arriba y al acceso sin conexión. Sin embargo, los administradores como usted, tienen acceso sin restricciones en la aplicación, a menos que estén sin conexión.",

    // advanced settings: prod tests
    "prodTests": "Pruebas de producción",
    "fileStorageTest": "Prueba de almacenamiento de archivos",
    "fileStorageTestDesc": "Use el siguiente botón para probar si el almacenamiento S3 está funcionando correctamente.",
    "fileStorageButton": "Probar configuración de S3",
    "fileStorageFail": "La configuración de S3 falló",
    "fileStorageSuccess": "La configuración de S3 está funcionando correctamente",
    "emailTest": "Prueba de correo electrónico",
    "emailTestDesc":
      "Use el siguiente botón para probar si su servidor puede enviar correos electrónicos correctamente. Un correo electrónico similar a un restablecimiento de contraseña debería ser entregado a la dirección de correo electrónico objetivo.",
    "targetEmail": "Correo electrónico objetivo",
    "emailTestButton": "Enviar correo de prueba",
    "emailTestFail": "La prueba de correo electrónico falló",
    "emailTestSuccess": "Correo enviado con éxito, por favor revise su bandeja de entrada.",
    "fail": "Fallar",
    "success": "Éxito",

    // login
    "login": "Iniciar sesión",
    "resetPassword": "Restablecer contraseña",
    "serverUrl": "URL del servidor",
    "proceedOffline": "Continuar sin conexión",
    "youLLGet": "Recibirás el enlace de restablecimiento por correo electrónico",
    "beenSent": "Las instrucciones para restablecer la contraseña se han enviado, revise su bandeja de entrada.",

    // other
    "sureArchiveSelected": "¿Está seguro de que desea archivar los elementos seleccionados?",
    "sureClosePanel": "¿Está seguro de que desea cerrar este panel? Se perderán los cambios no guardados.",
    "sure": "Seguro",
    "back": "Atrás",
    "firstLaunchDialogTitle": "Bienvenido a Apexo",
    "firstLaunchDialogContent":
      "Ha instalado Apexo con éxito. Sin embargo, para una mejor experiencia y para uso en el mundo real, tendrá algunas cosas que configurar. Escanee el código QR a continuación para comenzar.",
    "newVersionDialogTitle": "Nueva versión disponible",
    "newVersionDialogContent":
      "Una nueva versión de Apexo está disponible. Por favor, actualice a la última versión para obtener la mejor experiencia. Escanee el código QR a continuación para comenzar.",
  };
}
